export const MOCK_REQUESTS = [
  {
    id: '1',
    restaurant_name: 'The Larder',
    category: 'protein',
    item: 'Wagyu Strip Loin',
    quantity: '40 lbs',
    needed_by: '2026-06-28',
    notes: 'Must be USDA Prime, dry-aged minimum 21 days',
    status: 'open',
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: '2',
    restaurant_name: 'Oleander',
    category: 'produce',
    item: 'Heirloom Tomatoes',
    quantity: '25 lbs',
    needed_by: '2026-06-26',
    notes: 'Mixed varieties, no Roma',
    status: 'open',
    created_at: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: '3',
    restaurant_name: 'Salt & Stone',
    category: 'dairy',
    item: 'Burrata',
    quantity: '12 units (4oz each)',
    needed_by: '2026-06-27',
    notes: 'Fresh, same-day delivery preferred',
    status: 'open',
    created_at: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: '4',
    restaurant_name: 'Provision',
    category: 'dry_goods',
    item: 'Arborio Rice',
    quantity: '50 lbs',
    needed_by: '2026-07-01',
    notes: 'Vialone Nano acceptable',
    status: 'open',
    created_at: new Date(Date.now() - 900000).toISOString(),
  },
]

export const MOCK_BIDS = [
  {
    id: 'b1',
    request_id: '1',
    purveyor_name: 'Heritage Foods Supply',
    price_per_unit: 38.5,
    unit: 'lb',
    total_price: 1540,
    delivery_date: '2026-06-27',
    notes: 'Certified USDA Prime, 28-day dry aged',
    status: 'pending',
    created_at: new Date(Date.now() - 1200000).toISOString(),
  },
  {
    id: 'b2',
    request_id: '1',
    purveyor_name: 'Pacific Rim Provisions',
    price_per_unit: 34.0,
    unit: 'lb',
    total_price: 1360,
    delivery_date: '2026-06-28',
    notes: 'Australian Wagyu, 21-day aged',
    status: 'pending',
    created_at: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: 'b3',
    request_id: '2',
    purveyor_name: 'Coastal Farms Direct',
    price_per_unit: 4.2,
    unit: 'lb',
    total_price: 105,
    delivery_date: '2026-06-26',
    notes: 'Mixed heirlooms from Sonoma County',
    status: 'pending',
    created_at: new Date(Date.now() - 300000).toISOString(),
  },
]
